name: CI - Python Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Run Unit Tests
        run: |
          uv run --with pytest --with pytest-cov pytest -v --cov=scripts --cov-report=term-missing tests/
